version: 2.1

jobs:
  deploy_website:
    docker:
      - image: circleci/node
    environment:
      - GOOGLE_PROJECT_ID: "wearablemyfoot"
    steps:
      - checkout
      - run:
          name: Install Firebase Tools
          command: npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy to Firebase
          command: |
            pushd website
            ./firebase-deploy/node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --project $GOOGLE_PROJECT_ID
            popd

workflows:
  deploy_website:
    jobs:
      - deploy_website:
          filters:
            branches:
              only:
                - master
                - website
